### ISSUE TITLE
Where is the CQL?

### ISSUE THREAD

**Issue by 8JasonStatham8** [TroddenSpade/Decision-Transformer-on-Offline-Reinforcement-Learning#1]
I am sorry I couldn't find the implementation of CQL. Did you forget it?

**Comment by TroddenSpade** [comment]
Hi, @8JasonStatham8. Unfortunately, I forgot to upload the _CQL.ipynb_ file. I will promptly upload it once I find the notebook file. In the meantime, you can check out [Costa Huang's videos on implementing the CQL](https://www.youtube.com/watch?v=CY_LQ1wRY1U&list=PLQpKd36nzSuMynZLU2soIpNSMeXMplnKP&index=33).
